name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Client - Install Dependencies
        working-directory: ./client
        run: npm install

      - name: Client - Build Packages
        working-directory: ./client
        run: npm run build
